Creating 1D, 2D, and 3D tensors using NumPy.

In [ ]:
import numpy as np

tensor_1d = np.array([1, 2, 3, 4])
print(tensor_1d)

[1 2 3 4]


In [ ]:
tensor_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(tensor_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
tensor_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
print(tensor_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
print(tensor_1d.shape)
print(tensor_2d.shape)
print(tensor_3d.shape)

(4,)
(2, 3)
(2, 2, 3)


Creating 1D, 2D, and 3D tensors using PyTorch.

In [ ]:
import torch

tensor_1d = torch.tensor([1, 2, 3, 4])
print(tensor_1d)

tensor([1, 2, 3, 4])


In [ ]:
tensor_2d = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
print(tensor_2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
tensor_3d = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
print(tensor_3d)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


In [ ]:
tensor_1d.shape
tensor_2d.shape
tensor_3d.shape


torch.Size([2, 2, 3])

Basic Operations: Element-wise addition, subtraction, multiplication, and division.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

add = a + b
print(add)

sub = a - b
print(sub)

mul = a * b
print(mul)

div = a / b
print(div)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Adding Bias to Features : Broadcasting

In [ ]:
X = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])

bias = torch.tensor([0.1, 0.2, 0.3])

Y = X + bias
print(Y)

tensor([[1.1000, 2.2000, 3.3000],
        [4.1000, 5.2000, 6.3000]])


Dot Product (1D × 1D)

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot = np.dot(a, b)
print(dot)

32


Matrix–Vector Multiplication : (m×n)⋅(n)→(m)

In [ ]:
W = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])   # (2×3)

x = torch.tensor([1., 0., 1.])     # (3)

y = W @ x
print(y)


tensor([ 4., 10.])


Matrix Multiplication : (m×n)⋅(n×p)→(m×p)

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = A @ B
print(C)

[[19 22]
 [43 50]]


ML Example: Linear Layer

In [ ]:
# batch_size = 4, features = 3, outputs = 2
X = torch.randn(4, 3)
W = torch.randn(3, 2)
b = torch.randn(2)

Y = X @ W + b
print(Y.shape)

torch.Size([4, 2])


Indexing & Slicing : 1D Tensor

In [ ]:
x = np.array([10, 20, 30, 40, 50])

print(x[0])        # first element
print(x[-1])       # last element
print(x[1:4])

10
50
[20 30 40]


Indexing & Slicing : 2D Tensor (Matrix)

In [ ]:
X = torch.tensor([
    [1,  2,  3],
    [4,  5,  6],
    [7,  8,  9]
])

print(X[0])        # first row
print(X[:, 1])     # second column
print(X[0:2, 1:3]) # sub-matrix

tensor([1, 2, 3])
tensor([2, 5, 8])
tensor([[2, 3],
        [5, 6]])


Boolean Masking

In [ ]:
x = np.array([5, 12, 8, 20, 3])

mask = x > 10
print(mask)

filtered = x[mask]
print(filtered)

[False  True False  True False]
[12 20]


In [ ]:
X = torch.tensor([
    [1, 20, 3],
    [15, 5, 30],
    [2, 40, 6]
])

mask = X > 10
print(mask)

filtered = X[mask]
print(filtered)

tensor([[False,  True, False],
        [ True, False,  True],
        [False,  True, False]])
tensor([20, 15, 30, 40])


In [ ]:
# Conditional Replace
X = torch.tensor([1., 5., 10., 20.])

X[X < 10] = 0
print(X)

tensor([ 0.,  0., 10., 20.])


Extracting Subtensors

In [ ]:
image = torch.randn(3, 224, 224)

# Extract center crop
center_crop = image[:, 50:150, 50:150]

print(center_crop.shape)  # (3, 100, 100)

torch.Size([3, 100, 100])


.view() — Reshape WITHOUT copying

In [ ]:
import torch

x = torch.arange(12)      # shape: (12,)
y = x.view(3, 4)

print(y)
print(y.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


.reshape() — Safe Reshape

In [ ]:
x = torch.arange(12)

y = x.reshape(3, 4)
print(y)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


.unsqueeze() — Add a dimension

In [ ]:
x = torch.tensor([1, 2, 3])

print(x.shape)          # (3,)
print(x.unsqueeze(0))   # (1, 3)
print(x.unsqueeze(1))   # (3, 1)

torch.Size([3])
tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3]])


.squeeze() — Remove dimensions of size 1

In [ ]:
x = torch.randn(1, 3, 1, 224)

print(x.shape)
print(x.squeeze().shape)

torch.Size([1, 3, 1, 224])
torch.Size([3, 224])


In-place vs Out-of-place operations.

In [ ]:
import torch

x = torch.tensor([1., 2., 3.])

y = x + 1      # out-of-place
print(x)       # unchanged

x.add_(1)      # in-place
print(x)       # modified

tensor([1., 2., 3.])
tensor([2., 3., 4.])
